### ISSUE TITLE
Update Readme.md to mention Pressure2 DARK instead of Pressure2 (main theme) 

### ISSUE THREAD

**Issue by Ymetro** [CptDinosaur/Pressure2DarkPatch#1]
Hi, 
I noticed that you mention the standard Pressure2 theme to apply the patch to. 
I tested this and gave me weird results: allmost white text on the white background of the main Pressure2 theme, so I knew I was patching the wrong theme! 

When I applied the patch to the DARK version of Pressure2, it applied it correctly. 
Hence I like you to mention in the Installation part of your README.md that you have to download the Pressure2 DARK theme from the Pressure2 website and apply your patch to it. 

Kind Regards, 
Ymetro

**Comment by DoctorDinosaur** [comment]
The first line did say "Unofficial Patches for the Pressure²: Dark Version Steam Skin" but I'll make it clear in the instructions too if that'll help :)
