### ISSUE TITLE
Can drop down arrows in dropdown lists be white to match the text?

### ISSUE THREAD

**Issue by Ymetro** [CptDinosaur/Pressure2DarkPatch#2]
Hi,

Can the drop down menu arrow made white like the text? 
They are found on the following Settings pages:
- **Account** -  in the popup window after pressing the Bèta participation "Change" button; 
- **In game** - drop down menu beneath "In-game FPS counter" and "In-game server-browser: Max. pings / minute; 
- **In-Home Streaming** - in the popup window after pressing the "ADVANCED CLIENT OPTIONS"; 
- **Interface** - select startup window,  choose theme and choose language dropdown lists; 
- **Downloads** - region selection, limit bandwith to and between dropdown listis; 
- **Music** - in the folder selection window after pressing the "Add" button to add folders to the music library;
- **Broadcasting** - Privacy setting, videoresolution, maximum bitrate, optimize coding and show chat in game dropdown lists; 

And in other places like: 
- **Install [game]** - choose installation location dropdown menu; 
- **Backup destination** - in 2nd and 3rd page of the backup wizard; 
.. and probably more locations. 

Does every location need to be addressed or is it one color setting 'that rules them all'?

Kind Regards,
Ymetro

**Comment by DoctorDinosaur** [comment]
Fixed on the repo, but I'm going to try and fix some more bugs before I make a new release. Feel free to download it as a zip for now, and overwrite.
