### ISSUE TITLE
Broken UI with Steam Chat update

### ISSUE THREAD

**Issue by Vustom** [CptDinosaur/Pressure2DarkPatch#5]
Just wondering if this will be updated to support the new UI changes that came with the Steam Chat update?

**Comment by DoctorDinosaur** [comment]
I've stopped working on it for now as DirtDiglett has started work on fixing the main version of Pressure2, it's dev branch is still being updated. IMO though, I hate the new chat update, I've had to switch skin for now.

**Comment by Vustom** [comment]
After a little research you can switch back to the old chat with shortcut arguments `-nochatui -nofriendsui`, after this I merged the changes from [this post](https://steamcommunity.com/groups/pressureskin/discussions/0/3051633726576849955/#c1759104257590140537) with your patch and it's working pretty well.

**Comment by DoctorDinosaur** [comment]
Published a temporary fix while DirtDiglett works!
